services:
  postgres:
    image: postgres:16
    container_name: postgres_cdc
    restart: unless-stopped
    environment:
      POSTGRES_USER: cdc_user
      POSTGRES_PASSWORD: cdc_password
      POSTGRES_DB: cdc_db
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
